class Message:
    def __init__(self, language):
        self.language = language
        self.texts = {
            "EN": {
                "survey_title"          : "RedFlag - Toxic Guy Detector",
                "welcome_message"       : "Hello :blue[**{name}**]! :sunglasses:",
                "welcome_description"   : "It is so nice to see you here. This survey is designed to help you to see how :red[toxic] your boyfriend is :bomb:",
                "welcome_instruction"   : "Please feel free to answer all the questions so that we can analyze the results obtained from all girls and use them to better point the toxic guys.",
                "goodbye_message"       : "Thank you for completing the survey and providing feedback **{name}**! :confetti_ball:",
                "survey_complete_msg"   : "Thank you for completing the survey! Your boyfriend's toxic score is: **{toxic_score:.2f}**",
                "filter_fail_msg"       : "Unfortunately **{bf_name}** failed {filter_violations} filters. This should be a critical warning for you! :boom:",
                "filter_pass_msg"       : "Nice. **{bf_name}** satisfies all the filters :) :blossom:",
                "red_flag_fail_msg"     : "**{bf_name}** seems to have a high level of toxicity. :skull:",
                "red_flag_pass_msg"     : "**{bf_name}** is less toxic than many others. Good for him! :herb:" ,
                "name_input"            : "Name",
                "email_input"           : "Email",
                "bf_name_input"         : "Boyfriend's Name",
                "filter_header"         : "Filter Questions" ,
                'redflag_header'        : "Redflag Questions",
                "continue_msg"          : "Continue",
                "applicability_check"   : "Is this question applicable to you?",
                "not_applicable_msg"    : "Not Applicable",
                "select_score_msg"      : "Please select a score (0-10):",
                "select_option_msg"     : "Please select:",
                "boolean_answer"        : ["Yes", "No"],
                "limited_opt_answer"    : ["never", "1", "2", "3", "4", "5+"],
                "select_toxicity_msg"   : "So, how toxic is your boyfriend?",
                "toxicity_answer"       : ['not at all', 'a little bit', 'toxic but not more than others', 'yeah, a little more', 'he is literally a toxic guy'],
                "toxicity_result_msg"   : "This corresponds to a toxicity rating of **{toxicity_rating}**.",
                "toxic_graph_guy_cnt"   : "Number of guys in database: {guy_cnt}",
                "toxic_graph_msg"       : "blue dot is your guy! :large_blue_circle:",
                "toxic_graph_x"        : "Index (Sorted by Score)",
                "toxic_graph_y"        : "Toxicity",
                "feedback_msg"          : "How did you like the test:",
                "please_rate_msg"       : "Please provide a rating.",
                "sentiment_mapping"     : ["One", "Two", "Three", "Four", "Five"],
                "feedback_result_msg"   : "You selected {star} :star:.",
                "rating_result_msg"     : "You selected **{selected}**",
                "toxic_saved_msg"       : "Toxicity rating saved successfully!",
                "toxic_error_msg"       : "Error saving toxicity rating: {e}",
                "response_saved_msg"    : "Responses saved successfully!",
                "response_error_msg"    : "Error saving responses: {e}",
                "enter_details_msg"     : "Please enter your details:",
                "enter_valid_email_msg" : "Please enter a valid email address (e.g., example@domain.com).",
                "enter_name_msg"        : "Please enter your name.",
                "enter_bf_name_msg"     : "Please enter your boyfriend's name:",
                "enter_feedback_msg"    : "Please provide feedback :gift_heart:",
                "toxicity_header"       : "Let's evaluate your boyfriend's toxicity :tulip:",
                "fill_before_submit_msg": "Please complete the questions before submitting.",
                "name_submit_msg"       : "Please enter your name before submitting.",
                "gtk_header"            : "Let's get to know you :clipboard:",
                "toxicity_self_rating"  : "How do you think your boyfriend is toxic.. :man_dancing:",
                "result_header"         : "Result :dizzy:",
                "survey_complete_msg"   : "Finish",
                "start_new_survey"      : "Start New Survey",
                "toxic_score_info"      : "Your boyfriend's toxicity score is: {toxic_score}%",
                "filter_viol_info"      : "Generally, guys fail in {avg_filter_violations} filters.",
                "see_results"           : "See the result"

            },
            "TR": {
                "survey_title"          : "RedFlag - Toksik Sevgili Dedektörü",
                "welcome_message"       : "Merhaba :blue[**{name}**]! :sunglasses:",
                "welcome_description"   : "Burada seni görmek çok güzel. Bu anket, erkek arkadaşının ne kadar :red[toksik] olduğunu görmene yardımcı olmak için tasarlandı :bomb:",
                "welcome_instruction"   : "Lütfen tüm soruları cevaplamaktan çekinme, böylece tüm kızlardan elde edilen sonuçları analiz edebilir ve toksik erkekleri daha iyi tespit edebiliriz.",
                "goodbye_message"       : "Anketi tamamladığın ve geri bildirim verdiğin için teşekkürler **{name}**! :confetti_ball:",
                "survey_complete_msg"   : "Anketi tamamladığın için teşekkürler! Erkek arkadaşınızın toksiklik skoru: **{toxic_score:.2f}**",
                "filter_fail_msg"       : "**{bf_name}**, ne yazık ki {filter_violations} tane filtrede sınıfta kaldı. Bu senin için ciddi bir uyarı anlamına gelmeli! :boom:",
                "filter_pass_msg"       : "Güzel.. **{bf_name}** tüm filtrelerden geçti :) :blossom:",
                "red_flag_fail_msg"     : "**{bf_name}** toksiklik seviyesi biraz fazla yüksek. :skull:",
                "red_flag_pass_msg"     : "**{bf_name}** toksiklik seviyesi diğer erkeklere göre daha düşük. Aferin ona! :herb:",
                "name_input"            : "İsim",
                "email_input"           : "Eposta",
                "bf_name_input"         : "Erkek Arkadaşının İsmi",
                "filter_header"         : "Filtre Sorular",
                'redflag_header'        : "Redflag Soruları",
                "continue_msg"          : "Devam",
                "applicability_check"   : "Bu soru sizin için geçerli mi?",
                "not_applicable_msg"    : "Geçerli Değil",
                "select_score_msg"      : "Lütfen 0-10 arasında değerlendirin:",
                "select_option_msg"     : "Lütfen seçin:",
                "boolean_answer"        : ["Evet", "Hayır"],
                "limited_opt_answer"    : ["hiç", "1", "2", "3", "4", "5+"],
                "select_toxicity_msg"   : "Peki, sence erkek arkadaşın ne kadar toksik?:",
                "toxicity_answer"       : ['hiç değil', 'eh, birazcık', 'toksik ama herkes kadar', 'evet, biraz fazla toksik', 'gerçekten de toksik birisi'],
                "toxicity_result_msg"   : "Bu, **{toxicity_rating}** toksisite derecesine karşılık geliyor.",
                "toxic_graph_guy_cnt"   : "Veritabanındaki erkeklerin sayısı: {guy_cnt}",
                "toxic_graph_msg"       : "Mavi nokta seninki! :large_blue_circle:",
                "toxic_graph_x"        : "indeks (skora göre sıralı)",
                "toxic_graph_y"        : "Toksiklik",
                "feedback_msg"          : "Testi ne kadar beğendin:",
                "please_rate_msg"       : "Lütfen bir değerlendirme yapın.",
                "sentiment_mapping"     : ["Bir", "İki", "Üç", "Dört", "Beş"],
                "feedback_result_msg"   : "{star} :star: seçtin.",
                "rating_result_msg"     : "**{selected}** seçtin",
                "toxic_saved_msg"       : "Toksik değerlendirmen kaydedildi.",
                "toxic_error_msg"       : "Toksik değerlendirme kaydedilirken hata oluştu: {e}",
                "response_saved_msg"    : "Yanıtlarınız başarıyla kaydedildi.",
                "response_error_msg"    : "Yanıtlarınız kaydedilirken hata oluştu: {e}",
                "enter_details_msg"     : "Lütfen bilgilerinizi girin:",
                "enter_valid_email_msg" : "Lütfen geçerli bir e-posta adresi girin (örneğin, ornek@alanadi.com).",
                "enter_name_msg"        : "Lütfen adınızı girin.",
                "enter_bf_name_msg"     : "Lütfen erkek arkadaşınızın adını girin:",
                "enter_feedback_msg"    : "Lütfen geri bildirim verin :gift_heart:",
                "toxicity_header"       : "Haydi erkek arkadaşının toksikliğini değerlendirelim :tulip:",
                "fill_before_submit_msg": "Göndermeden önce lütfen soruları yanıtlayın.",
                "name_submit_msg"       : "Göndermeden önce lütfen adınızı girin.",
                "gtk_header"            : "Seni tanıyalım :clipboard:",
                "toxicity_self_rating"  : "Sence, erkek arkadaşın ne kadar toksik.. :man_dancing:",
                "result_header"         : "Sonuç :dizzy:",
                "survey_complete_msg"   : "Bitir",
                "start_new_survey"      : "Yeni Anket Başlat",
                "toxic_score_info"      : "Erkek arkadaşının toksiklik skoru: %{toxic_score}",
                "filter_viol_info"      : "Genelde {avg_filter_violations} filtreye takılıyor erkekler.",
                "see_results"           : "Sonucu gör"



            }
        }

    def get_text(self, key, **kwargs):
        text = self.texts[self.language][key]
        if isinstance(text, str):  # Only format if it's a string
            return text.format(**kwargs)
        return text  # Return as-is for lists
    